title: OAF Workshop
only_build_toc_files: true
execute:
    execute_notebooks: force
    timeout: 90
sphinx:
    config:
        nb_custom_formats:
            .py:
                - jupytext.reads
                - fmt: py:percent
        suppress_warnings:
            - ref.myst
            - mystnb.unknown_mime_type
exclude_patterns:
  - ".pytest_cache"
  - "**/.pytest_cache"
  - "ENV"
thebe:
  activate: true
  binderhub_url: "https://mybinder.org"
  repository_url: "https://github.com/martvald/oaf-3d-vision-pipeline-workshop"
  branch: "main"
launch_buttons:
    thebe: true
