title: OAF Workshop
only_build_toc_files: true
execute:
    execute_notebooks: force
    timeout: 30
sphinx:
    config:
        nb_custom_formats:
            .py:
                - jupytext.reads
                - fmt: py:percent
        suppress_warnings:
            - ref.myst
            - mystnb.unknown_mime_type
exclude_patterns:
  - '.pytest_cache'
  - '**/.pytest_cache'
  - 'ENV'   