name: Publish Website
on: 
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  jupyter_book:
    name: Jupyter Book
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest -e . -e ci/ci_tools
    - name: Validate Table of Contents
      run: python -m pytest --verbose ci/ci_tools/ci_tools/documentation/validate_toc.py
    - name: Build Jupyter Book
      run: jupyter-book build . --warningiserror
    - name: Upload Jupyter Book
      uses: actions/upload-pages-artifact@v2
      with:
        path: _build/html
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
